C:\Users\Inga\PycharmProjects\Baigiamas_darbas\.venv\Scripts\python.exe C:\Users\Inga\PycharmProjects\Baigiamas_darbas\meteo.py
{
    "place": {
        "code": "ziegzdriai",
        "name": "\u017dieg\u017edriai",
        "administrativeDivision": "Kauno rajono savivaldyb\u0117",
        "country": "Lietuva",
        "countryCode": "LT",
        "coordinates": {
            "latitude": 54.88716,
            "longitude": 24.09111
        }
    },
    "forecastType": "long-term",
    "forecastCreationTimeUtc": "2024-12-30 17:01:31",
    "forecastTimestamps": [
        {
            "forecastTimeUtc": "2024-12-30 18:00:00",
            "airTemperature": 5.2,
            "feelsLikeTemperature": 1.1,
            "windSpeed": 6,
            "windGust": 11,
            "windDirection": 249,
            "cloudCover": 100,
            "seaLevelPressure": 1014,
            "relativeHumidity": 97,
            "totalPrecipitation": 0.5,
            "conditionCode": "rain"
        },
        {
            "forecastTimeUtc": "2024-12-30 19:00:00",
            "airTemperature": 5.2,
            "feelsLikeTemperature": 1.1,
            "windSpeed": 6,
            "windGust": 11,
            "windDirection": 250,
            "cloudCover": 100,
            "seaLevelPressure": 1014,
            "relativeHumidity": 97,
            "totalPrecipitation": 0.4,
            "conditionCode": "rain"
        },
        {
            "forecastTimeUtc": "2024-12-30 20:00:00",
            "airTemperature": 5.3,
            "feelsLikeTemperature": 0.9,
            "windSpeed": 7,
            "windGust": 12,
            "windDirection": 248,
            "cloudCover": 100,
            "seaLevelPressure": 1013,
            "relativeHumidity": 97,
            "totalPrecipitation": 0.3,
            "conditionCode": "light-rain"
        },
        {
            "forecastTimeUtc": "2024-12-30 21:00:00",
            "airTemperature": 5.2,
            "feelsLikeTemperature": 0.7,
            "windSpeed": 7,
            "windGust": 12,
            "windDirection": 246,
            "cloudCover": 100,
            "seaLevelPressure": 1013,
            "relativeHumidity": 97,
            "totalPrecipitation": 0.3,
            "conditionCode": "light-rain"
        },
        {
            "forecastTimeUtc": "2024-12-30 22:00:00",
            "airTemperature": 5.2,
            "feelsLikeTemperature": 0.7,
            "windSpeed": 7,
            "windGust": 13,
            "windDirection": 250,
            "cloudCover": 100,
            "seaLevelPressure": 1013,
            "relativeHumidity": 96,
            "totalPrecipitation": 0.5,
            "conditionCode": "rain"
        },
        {
            "forecastTimeUtc": "2024-12-30 23:00:00",
            "airTemperature": 5.1,
            "feelsLikeTemperature": 0.3,
            "windSpeed": 8,
            "windGust": 14,
            "windDirection": 251,
            "cloudCover": 100,
            "seaLevelPressure": 1013,
            "relativeHumidity": 95,
            "totalPrecipitation": 0.6,
            "conditionCode": "rain"
        },
        {
            "forecastTimeUtc": "2024-12-31 00:00:00",
            "airTemperature": 4.9,
            "feelsLikeTemperature": 0,
            "windSpeed": 8,
            "windGust": 14,
            "windDirection": 250,
            "cloudCover": 100,
            "seaLevelPressure": 1012,
            "relativeHumidity": 95,
            "totalPrecipitation": 0.5,
            "conditionCode": "rain"
        },
        {
            "forecastTimeUtc": "2024-12-31 01:00:00",
            "airTemperature": 4.9,
            "feelsLikeTemperature": -0.3,
            "windSpeed": 9,
            "windGust": 15,
            "windDirection": 251,
            "cloudCover": 100,
            "seaLevelPressure": 1012,
            "relativeHumidity": 94,
            "totalPrecipitation": 0.2,
            "conditionCode": "light-rain"
        },
        {
            "forecastTimeUtc": "2024-12-31 02:00:00",
            "airTemperature": 4.9,
            "feelsLikeTemperature": -0.3,
            "windSpeed": 9,
            "windGust": 15,
            "windDirection": 254,
            "cloudCover": 100,
            "seaLevelPressure": 1012,
            "relativeHumidity": 94,
            "totalPrecipitation": 0.1,
            "conditionCode": "light-rain"
        },
        {
            "forecastTimeUtc": "2024-12-31 03:00:00",
            "airTemperature": 4.7,
            "feelsLikeTemperature": -0.5,
            "windSpeed": 9,
            "windGust": 16,
            "windDirection": 254,
            "cloudCover": 100,
            "seaLevelPressure": 1011,
            "relativeHumidity": 95,
            "totalPrecipitation": 0.2,
            "conditionCode": "light-rain"
        },
        {
            "forecastTimeUtc": "2024-12-31 04:00:00",
            "airTemperature": 4.8,
            "feelsLikeTemperature": -0.4,
            "windSpeed": 9,
            "windGust": 16,
            "windDirection": 256,
            "cloudCover": 100,
            "seaLevelPressure": 1011,
            "relativeHumidity": 95,
            "totalPrecipitation": 0.2,
            "conditionCode": "light-rain"
        },
        {
            "forecastTimeUtc": "2024-12-31 05:00:00",
            "airTemperature": 5,
            "feelsLikeTemperature": -0.2,
            "windSpeed": 9,
            "windGust": 15,
            "windDirection": 260,
            "cloudCover": 100,
            "seaLevelPressure": 1011,
            "relativeHumidity": 96,
            "totalPrecipitation": 0.3,
            "conditionCode": "light-rain"
        },
        {
            "forecastTimeUtc": "2024-12-31 06:00:00",
            "airTemperature": 5.4,
            "feelsLikeTemperature": 0.7,
            "windSpeed": 8,
            "windGust": 15,
            "windDirection": 265,
            "cloudCover": 100,
            "seaLevelPressure": 1012,
            "relativeHumidity": 96,
            "totalPrecipitation": 0.3,
            "conditionCode": "light-rain"
        },
        {
            "forecastTimeUtc": "2024-12-31 07:00:00",
            "airTemperature": 5.9,
            "feelsLikeTemperature": 1.6,
            "windSpeed": 7,
            "windGust": 14,
            "windDirection": 277,
            "cloudCover": 100,
            "seaLevelPressure": 1012,
            "relativeHumidity": 96,
            "totalPrecipitation": 0.8,
            "conditionCode": "rain"
        },
        {
            "forecastTimeUtc": "2024-12-31 08:00:00",
            "airTemperature": 5.9,
            "feelsLikeTemperature": 2,
            "windSpeed": 6,
            "windGust": 13,
            "windDirection": 291,
            "cloudCover": 100,
            "seaLevelPressure": 1013,
            "relativeHumidity": 94,
            "totalPrecipitation": 0.2,
            "conditionCode": "light-rain"
        },
        {
            "forecastTimeUtc": "2024-12-31 09:00:00",
            "airTemperature": 5.4,
            "feelsLikeTemperature": 1.4,
            "windSpeed": 6,
            "windGust": 11,
            "windDirection": 295,
            "cloudCover": 100,
            "seaLevelPressure": 1015,
            "relativeHumidity": 87,
            "totalPrecipitation": 0,
            "conditionCode": "cloudy"
        },
        {
            "forecastTimeUtc": "2024-12-31 10:00:00",
            "airTemperature": 5,
            "feelsLikeTemperature": 1.3,
            "windSpeed": 5,
            "windGust": 11,
            "windDirection": 288,
            "cloudCover": 100,
            "seaLevelPressure": 1016,
            "relativeHumidity": 83,
            "totalPrecipitation": 0,
            "conditionCode": "cloudy"
        },
        {
            "forecastTimeUtc": "2024-12-31 11:00:00",
            "airTemperature": 4.6,
            "feelsLikeTemperature": 0.8,
            "windSpeed": 5,
            "windGust": 9,
            "windDirection": 284,
            "cloudCover": 100,
            "seaLevelPressure": 1016,
            "relativeHumidity": 82,
            "totalPrecipitation": 0,
            "conditionCode": "cloudy"
        },
        {
            "forecastTimeUtc": "2024-12-31 12:00:00",
            "airTemperature": 4.3,
            "feelsLikeTemperature": 1,
            "windSpeed": 4,
            "windGust": 9,
            "windDirection": 282,
            "cloudCover": 100,
            "seaLevelPressure": 1017,
            "relativeHumidity": 79,
            "totalPrecipitation": 0,
            "conditionCode": "cloudy"
        },
        {
            "forecastTimeUtc": "2024-12-31 13:00:00",
            "airTemperature": 4,
            "feelsLikeTemperature": 0.6,
            "windSpeed": 4,
            "windGust": 8,
            "windDirection": 274,
            "cloudCover": 100,
            "seaLevelPressure": 1017,
            "relativeHumidity": 79,
            "totalPrecipitation": 0,
            "conditionCode": "cloudy"
        },
        {
            "forecastTimeUtc": "2024-12-31 14:00:00",
            "airTemperature": 3.5,
            "feelsLikeTemperature": 0,
            "windSpeed": 4,
            "windGust": 7,
            "windDirection": 269,
            "cloudCover": 100,
            "seaLevelPressure": 1017,
            "relativeHumidity": 84,
            "totalPrecipitation": 0,
            "conditionCode": "cloudy"
        },
        {
            "forecastTimeUtc": "2024-12-31 15:00:00",
            "airTemperature": 3.6,
            "feelsLikeTemperature": 0.8,
            "windSpeed": 3,
            "windGust": 6,
            "windDirection": 264,
            "cloudCover": 100,
            "seaLevelPressure": 1018,
            "relativeHumidity": 86,
            "totalPrecipitation": 0,
            "conditionCode": "cloudy"
        },
        {
            "forecastTimeUtc": "2024-12-31 16:00:00",
            "airTemperature": 3.7,
            "feelsLikeTemperature": 0.9,
            "windSpeed": 3,
            "windGust": 6,
            "windDirection": 258,
            "cloudCover": 100,
            "seaLevelPressure": 1018,
            "relativeHumidity": 85,
            "totalPrecipitation": 0,
            "conditionCode": "cloudy"
        },
        {
            "forecastTimeUtc": "2024-12-31 17:00:00",
            "airTemperature": 3.7,
            "feelsLikeTemperature": 0.9,
            "windSpeed": 3,
            "windGust": 5,
            "windDirection": 251,
            "cloudCover": 100,
            "seaLevelPressure": 1018,
            "relativeHumidity": 86,
            "totalPrecipitation": 0,
            "conditionCode": "cloudy"
        },
        {
            "forecastTimeUtc": "2024-12-31 18:00:00",
            "airTemperature": 3.6,
            "feelsLikeTemperature": 0.8,
            "windSpeed": 3,
            "windGust": 5,
            "windDirection": 235,
            "cloudCover": 100,
            "seaLevelPressure": 1018,
            "relativeHumidity": 86,
            "totalPrecipitation": 0,
            "conditionCode": "cloudy"
        },
        {
            "forecastTimeUtc": "2024-12-31 19:00:00",
            "airTemperature": 3.6,
            "feelsLikeTemperature": 0.8,
            "windSpeed": 3,
            "windGust": 5,
            "windDirection": 238,
            "cloudCover": 100,
            "seaLevelPressure": 1017,
            "relativeHumidity": 85,
            "totalPrecipitation": 0,
            "conditionCode": "cloudy"
        },
        {
            "forecastTimeUtc": "2024-12-31 20:00:00",
            "airTemperature": 3.2,
            "feelsLikeTemperature": 1.3,
            "windSpeed": 2,
            "windGust": 5,
            "windDirection": 196,
            "cloudCover": 100,
            "seaLevelPressure": 1017,
            "relativeHumidity": 93,
            "totalPrecipitation": 0,
            "conditionCode": "cloudy"
        },
        {
            "forecastTimeUtc": "2024-12-31 21:00:00",
            "airTemperature": 3.5,
            "feelsLikeTemperature": 0.7,
            "windSpeed": 3,
            "windGust": 5,
            "windDirection": 185,
            "cloudCover": 100,
            "seaLevelPressure": 1016,
            "relativeHumidity": 98,
            "totalPrecipitation": 0.1,
            "conditionCode": "light-rain"
        },
        {
            "forecastTimeUtc": "2024-12-31 22:00:00",
            "airTemperature": 4.6,
            "feelsLikeTemperature": 0.8,
            "windSpeed": 5,
            "windGust": 9,
            "windDirection": 215,
            "cloudCover": 100,
            "seaLevelPressure": 1015,
            "relativeHumidity": 99,
            "totalPrecipitation": 0,
            "conditionCode": "cloudy"
        },
        {
            "forecastTimeUtc": "2024-12-31 23:00:00",
            "airTemperature": 4.6,
            "feelsLikeTemperature": 0,
            "windSpeed": 7,
            "windGust": 12,
            "windDirection": 214,
            "cloudCover": 100,
            "seaLevelPressure": 1014,
            "relativeHumidity": 97,
            "totalPrecipitation": 0,
            "conditionCode": "cloudy"
        },
        {
            "forecastTimeUtc": "2025-01-01 00:00:00",
            "airTemperature": 4.1,
            "feelsLikeTemperature": -1,
            "windSpeed": 8,
            "windGust": 15,
            "windDirection": 219,
            "cloudCover": 100,
            "seaLevelPressure": 1013,
            "relativeHumidity": 95,
            "totalPrecipitation": 0,
            "conditionCode": "cloudy"
        },
        {
            "forecastTimeUtc": "2025-01-01 01:00:00",
            "airTemperature": 3.6,
            "feelsLikeTemperature": -1.7,
            "windSpeed": 8,
            "windGust": 15,
            "windDirection": 221,
            "cloudCover": 100,
            "seaLevelPressure": 1012,
            "relativeHumidity": 88,
            "totalPrecipitation": 0,
            "conditionCode": "cloudy"
        },
        {
            "forecastTimeUtc": "2025-01-01 02:00:00",
            "airTemperature": 2.5,
            "feelsLikeTemperature": -3.1,
            "windSpeed": 8,
            "windGust": 14,
            "windDirection": 224,
            "cloudCover": 100,
            "seaLevelPressure": 1010,
            "relativeHumidity": 87,
            "totalPrecipitation": 0,
            "conditionCode": "cloudy"
        },
        {
            "forecastTimeUtc": "2025-01-01 03:00:00",
            "airTemperature": 1.7,
            "feelsLikeTemperature": -3.7,
            "windSpeed": 7,
            "windGust": 13,
            "windDirection": 231,
            "cloudCover": 100,
            "seaLevelPressure": 1009,
            "relativeHumidity": 86,
            "totalPrecipitation": 0,
            "conditionCode": "cloudy"
        },
        {
            "forecastTimeUtc": "2025-01-01 04:00:00",
            "airTemperature": 1.4,
            "feelsLikeTemperature": -4.5,
            "windSpeed": 8,
            "windGust": 14,
            "windDirection": 244,
            "cloudCover": 100,
            "seaLevelPressure": 1009,
            "relativeHumidity": 87,
            "totalPrecipitation": 0,
            "conditionCode": "cloudy"
        },
        {
            "forecastTimeUtc": "2025-01-01 05:00:00",
            "airTemperature": 1.1,
            "feelsLikeTemperature": -4.9,
            "windSpeed": 8,
            "windGust": 14,
            "windDirection": 231,
            "cloudCover": 100,
            "seaLevelPressure": 1008,
            "relativeHumidity": 88,
            "totalPrecipitation": 0,
            "conditionCode": "cloudy"
        },
        {
            "forecastTimeUtc": "2025-01-01 06:00:00",
            "airTemperature": 1.3,
            "feelsLikeTemperature": -4.7,
            "windSpeed": 8,
            "windGust": 14,
            "windDirection": 231,
            "cloudCover": 100,
            "seaLevelPressure": 1007,
            "relativeHumidity": 89,
            "totalPrecipitation": 0,
            "conditionCode": "cloudy"
        },
        {
            "forecastTimeUtc": "2025-01-01 07:00:00",
            "airTemperature": 1.2,
            "feelsLikeTemperature": -4.4,
            "windSpeed": 7,
            "windGust": 14,
            "windDirection": 229,
            "cloudCover": 100,
            "seaLevelPressure": 1006,
            "relativeHumidity": 94,
            "totalPrecipitation": 0.3,
            "conditionCode": "sleet"
        },
        {
            "forecastTimeUtc": "2025-01-01 08:00:00",
            "airTemperature": 1.3,
            "feelsLikeTemperature": -4.3,
            "windSpeed": 7,
            "windGust": 13,
            "windDirection": 228,
            "cloudCover": 100,
            "seaLevelPressure": 1006,
            "relativeHumidity": 96,
            "totalPrecipitation": 0.4,
            "conditionCode": "sleet"
        },
        {
            "forecastTimeUtc": "2025-01-01 09:00:00",
            "airTemperature": 1.6,
            "feelsLikeTemperature": -4.3,
            "windSpeed": 8,
            "windGust": 13,
            "windDirection": 231,
            "cloudCover": 100,
            "seaLevelPressure": 1005,
            "relativeHumidity": 97,
            "totalPrecipitation": 0.5,
            "conditionCode": "rain"
        },
        {
            "forecastTimeUtc": "2025-01-01 10:00:00",
            "airTemperature": 2.2,
            "feelsLikeTemperature": -3.5,
            "windSpeed": 8,
            "windGust": 14,
            "windDirection": 234,
            "cloudCover": 100,
            "seaLevelPressure": 1004,
            "relativeHumidity": 96,
            "totalPrecipitation": 0.5,
            "conditionCode": "rain"
        },
        {
            "forecastTimeUtc": "2025-01-01 11:00:00",
            "airTemperature": 2.9,
            "feelsLikeTemperature": -2.6,
            "windSpeed": 8,
            "windGust": 14,
            "windDirection": 236,
            "cloudCover": 100,
            "seaLevelPressure": 1003,
            "relativeHumidity": 95,
            "totalPrecipitation": 0.5,
            "conditionCode": "rain"
        },
        {
            "forecastTimeUtc": "2025-01-01 12:00:00",
            "airTemperature": 3.3,
            "feelsLikeTemperature": -2.1,
            "windSpeed": 8,
            "windGust": 15,
            "windDirection": 235,
            "cloudCover": 100,
            "seaLevelPressure": 1003,
            "relativeHumidity": 95,
            "totalPrecipitation": 0.3,
            "conditionCode": "light-rain"
        },
        {
            "forecastTimeUtc": "2025-01-01 13:00:00",
            "airTemperature": 3.6,
            "feelsLikeTemperature": -1.7,
            "windSpeed": 8,
            "windGust": 15,
            "windDirection": 235,
            "cloudCover": 100,
            "seaLevelPressure": 1002,
            "relativeHumidity": 95,
            "totalPrecipitation": 0.2,
            "conditionCode": "light-rain"
        },
        {
            "forecastTimeUtc": "2025-01-01 14:00:00",
            "airTemperature": 3.9,
            "feelsLikeTemperature": -1.3,
            "windSpeed": 8,
            "windGust": 15,
            "windDirection": 236,
            "cloudCover": 100,
            "seaLevelPressure": 1002,
            "relativeHumidity": 94,
            "totalPrecipitation": 0.1,
            "conditionCode": "light-rain"
        },
        {
            "forecastTimeUtc": "2025-01-01 15:00:00",
            "airTemperature": 4.1,
            "feelsLikeTemperature": -1,
            "windSpeed": 8,
            "windGust": 15,
            "windDirection": 235,
            "cloudCover": 100,
            "seaLevelPressure": 1001,
            "relativeHumidity": 94,
            "totalPrecipitation": 0.1,
            "conditionCode": "light-rain"
        },
        {
            "forecastTimeUtc": "2025-01-01 16:00:00",
            "airTemperature": 4,
            "feelsLikeTemperature": -1.1,
            "windSpeed": 8,
            "windGust": 15,
            "windDirection": 233,
            "cloudCover": 100,
            "seaLevelPressure": 1001,
            "relativeHumidity": 95,
            "totalPrecipitation": 0.2,
            "conditionCode": "light-rain"
        },
        {
            "forecastTimeUtc": "2025-01-01 17:00:00",
            "airTemperature": 4,
            "feelsLikeTemperature": -1.1,
            "windSpeed": 8,
            "windGust": 15,
            "windDirection": 232,
            "cloudCover": 100,
            "seaLevelPressure": 1000,
            "relativeHumidity": 95,
            "totalPrecipitation": 0.5,
            "conditionCode": "rain"
        },
        {
            "forecastTimeUtc": "2025-01-01 18:00:00",
            "airTemperature": 4,
            "feelsLikeTemperature": -1.1,
            "windSpeed": 8,
            "windGust": 15,
            "windDirection": 232,
            "cloudCover": 100,
            "seaLevelPressure": 999,
            "relativeHumidity": 95,
            "totalPrecipitation": 0.5,
            "conditionCode": "rain"
        },
        {
            "forecastTimeUtc": "2025-01-01 19:00:00",
            "airTemperature": 4,
            "feelsLikeTemperature": -1.5,
            "windSpeed": 9,
            "windGust": 15,
            "windDirection": 230,
            "cloudCover": 100,
            "seaLevelPressure": 999,
            "relativeHumidity": 95,
            "totalPrecipitation": 0.6,
            "conditionCode": "rain"
        },
        {
            "forecastTimeUtc": "2025-01-01 20:00:00",
            "airTemperature": 3.9,
            "feelsLikeTemperature": -1.6,
            "windSpeed": 9,
            "windGust": 15,
            "windDirection": 230,
            "cloudCover": 100,
            "seaLevelPressure": 998,
            "relativeHumidity": 95,
            "totalPrecipitation": 0.7,
            "conditionCode": "rain"
        },
        {
            "forecastTimeUtc": "2025-01-01 21:00:00",
            "airTemperature": 3.5,
            "feelsLikeTemperature": -1.8,
            "windSpeed": 8,
            "windGust": 15,
            "windDirection": 229,
            "cloudCover": 100,
            "seaLevelPressure": 997,
            "relativeHumidity": 95,
            "totalPrecipitation": 1,
            "conditionCode": "rain"
        },
        {
            "forecastTimeUtc": "2025-01-02 00:00:00",
            "airTemperature": 4.6,
            "feelsLikeTemperature": -0.4,
            "windSpeed": 8,
            "windGust": 15,
            "windDirection": 231,
            "cloudCover": 100,
            "seaLevelPressure": 992,
            "relativeHumidity": 79,
            "totalPrecipitation": 0.7,
            "conditionCode": "rain"
        },
        {
            "forecastTimeUtc": "2025-01-02 03:00:00",
            "airTemperature": 4.9,
            "feelsLikeTemperature": 0,
            "windSpeed": 8,
            "windGust": 18,
            "windDirection": 235,
            "cloudCover": 100,
            "seaLevelPressure": 988,
            "relativeHumidity": 87,
            "totalPrecipitation": 1.1,
            "conditionCode": "rain"
        },
        {
            "forecastTimeUtc": "2025-01-02 06:00:00",
            "airTemperature": 3.5,
            "feelsLikeTemperature": -2.1,
            "windSpeed": 9,
            "windGust": 19,
            "windDirection": 250,
            "cloudCover": 7,
            "seaLevelPressure": 990,
            "relativeHumidity": 77,
            "totalPrecipitation": 0.1,
            "conditionCode": "light-rain"
        },
        {
            "forecastTimeUtc": "2025-01-02 09:00:00",
            "airTemperature": 1.6,
            "feelsLikeTemperature": -3.4,
            "windSpeed": 6,
            "windGust": 13,
            "windDirection": 263,
            "cloudCover": 100,
            "seaLevelPressure": 996,
            "relativeHumidity": 86,
            "totalPrecipitation": 0.3,
            "conditionCode": "light-snow"
        },
        {
            "forecastTimeUtc": "2025-01-02 12:00:00",
            "airTemperature": 1.4,
            "feelsLikeTemperature": -3.2,
            "windSpeed": 5,
            "windGust": 10,
            "windDirection": 266,
            "cloudCover": 76,
            "seaLevelPressure": 998,
            "relativeHumidity": 83,
            "totalPrecipitation": 1.5,
            "conditionCode": "heavy-snow"
        },
        {
            "forecastTimeUtc": "2025-01-02 15:00:00",
            "airTemperature": -0.4,
            "feelsLikeTemperature": -4.8,
            "windSpeed": 4,
            "windGust": 10,
            "windDirection": 269,
            "cloudCover": 6,
            "seaLevelPressure": 1001,
            "relativeHumidity": 82,
            "totalPrecipitation": 0.4,
            "conditionCode": "light-snow"
        },
        {
            "forecastTimeUtc": "2025-01-02 18:00:00",
            "airTemperature": -1.9,
            "feelsLikeTemperature": -6.6,
            "windSpeed": 4,
            "windGust": 9,
            "windDirection": 264,
            "cloudCover": 98,
            "seaLevelPressure": 1003,
            "relativeHumidity": 88,
            "totalPrecipitation": 0,
            "conditionCode": "cloudy"
        },
        {
            "forecastTimeUtc": "2025-01-02 21:00:00",
            "airTemperature": -1.5,
            "feelsLikeTemperature": -6.1,
            "windSpeed": 4,
            "windGust": 9,
            "windDirection": 243,
            "cloudCover": 4,
            "seaLevelPressure": 1004,
            "relativeHumidity": 87,
            "totalPrecipitation": 0,
            "conditionCode": "clear"
        },
        {
            "forecastTimeUtc": "2025-01-03 00:00:00",
            "airTemperature": -1.8,
            "feelsLikeTemperature": -7.2,
            "windSpeed": 5,
            "windGust": 10,
            "windDirection": 224,
            "cloudCover": 5,
            "seaLevelPressure": 1003,
            "relativeHumidity": 88,
            "totalPrecipitation": 0,
            "conditionCode": "clear"
        },
        {
            "forecastTimeUtc": "2025-01-03 03:00:00",
            "airTemperature": -1.3,
            "feelsLikeTemperature": -7.1,
            "windSpeed": 6,
            "windGust": 12,
            "windDirection": 236,
            "cloudCover": 95,
            "seaLevelPressure": 1002,
            "relativeHumidity": 78,
            "totalPrecipitation": 0.3,
            "conditionCode": "light-snow"
        },
        {
            "forecastTimeUtc": "2025-01-03 06:00:00",
            "airTemperature": -1.4,
            "feelsLikeTemperature": -6.7,
            "windSpeed": 5,
            "windGust": 13,
            "windDirection": 250,
            "cloudCover": 60,
            "seaLevelPressure": 1002,
            "relativeHumidity": 84,
            "totalPrecipitation": 0,
            "conditionCode": "cloudy-with-sunny-intervals"
        },
        {
            "forecastTimeUtc": "2025-01-03 09:00:00",
            "airTemperature": -0.9,
            "feelsLikeTemperature": -6.1,
            "windSpeed": 5,
            "windGust": 11,
            "windDirection": 241,
            "cloudCover": 91,
            "seaLevelPressure": 1004,
            "relativeHumidity": 81,
            "totalPrecipitation": 0,
            "conditionCode": "cloudy"
        },
        {
            "forecastTimeUtc": "2025-01-03 12:00:00",
            "airTemperature": -0.4,
            "feelsLikeTemperature": -5.4,
            "windSpeed": 5,
            "windGust": 10,
            "windDirection": 247,
            "cloudCover": 48,
            "seaLevelPressure": 1004,
            "relativeHumidity": 68,
            "totalPrecipitation": 0,
            "conditionCode": "partly-cloudy"
        },
        {
            "forecastTimeUtc": "2025-01-03 15:00:00",
            "airTemperature": -1.4,
            "feelsLikeTemperature": -6.7,
            "windSpeed": 5,
            "windGust": 11,
            "windDirection": 245,
            "cloudCover": 79,
            "seaLevelPressure": 1004,
            "relativeHumidity": 88,
            "totalPrecipitation": 0,
            "conditionCode": "cloudy"
        },
        {
            "forecastTimeUtc": "2025-01-03 18:00:00",
            "airTemperature": -1.9,
            "feelsLikeTemperature": -6.6,
            "windSpeed": 4,
            "windGust": 11,
            "windDirection": 239,
            "cloudCover": 100,
            "seaLevelPressure": 1004,
            "relativeHumidity": 80,
            "totalPrecipitation": 1.3,
            "conditionCode": "heavy-snow"
        },
        {
            "forecastTimeUtc": "2025-01-03 21:00:00",
            "airTemperature": -1,
            "feelsLikeTemperature": -6.7,
            "windSpeed": 6,
            "windGust": 12,
            "windDirection": 211,
            "cloudCover": 100,
            "seaLevelPressure": 1001,
            "relativeHumidity": 85,
            "totalPrecipitation": 0.3,
            "conditionCode": "light-snow"
        },
        {
            "forecastTimeUtc": "2025-01-04 00:00:00",
            "airTemperature": -0.7,
            "feelsLikeTemperature": -6.4,
            "windSpeed": 6,
            "windGust": 14,
            "windDirection": 203,
            "cloudCover": 93,
            "seaLevelPressure": 997,
            "relativeHumidity": 83,
            "totalPrecipitation": 0.8,
            "conditionCode": "snow"
        },
        {
            "forecastTimeUtc": "2025-01-04 03:00:00",
            "airTemperature": -1.6,
            "feelsLikeTemperature": -6.9,
            "windSpeed": 5,
            "windGust": 13,
            "windDirection": 304,
            "cloudCover": 45,
            "seaLevelPressure": 995,
            "relativeHumidity": 89,
            "totalPrecipitation": 0.8,
            "conditionCode": "snow"
        },
        {
            "forecastTimeUtc": "2025-01-04 06:00:00",
            "airTemperature": -2.7,
            "feelsLikeTemperature": -8.3,
            "windSpeed": 5,
            "windGust": 17,
            "windDirection": 301,
            "cloudCover": 10,
            "seaLevelPressure": 1003,
            "relativeHumidity": 85,
            "totalPrecipitation": 0.5,
            "conditionCode": "light-snow"
        },
        {
            "forecastTimeUtc": "2025-01-04 09:00:00",
            "airTemperature": -3.5,
            "feelsLikeTemperature": -8.6,
            "windSpeed": 4,
            "windGust": 10,
            "windDirection": 283,
            "cloudCover": 0,
            "seaLevelPressure": 1007,
            "relativeHumidity": 88,
            "totalPrecipitation": 0,
            "conditionCode": "clear"
        },
        {
            "forecastTimeUtc": "2025-01-04 12:00:00",
            "airTemperature": -3,
            "feelsLikeTemperature": -7.1,
            "windSpeed": 3,
            "windGust": 10,
            "windDirection": 295,
            "cloudCover": 28,
            "seaLevelPressure": 1010,
            "relativeHumidity": 88,
            "totalPrecipitation": 0,
            "conditionCode": "partly-cloudy"
        },
        {
            "forecastTimeUtc": "2025-01-04 15:00:00",
            "airTemperature": -5.4,
            "feelsLikeTemperature": -8.8,
            "windSpeed": 2,
            "windGust": 7,
            "windDirection": 288,
            "cloudCover": 15,
            "seaLevelPressure": 1012,
            "relativeHumidity": 93,
            "totalPrecipitation": 0,
            "conditionCode": "clear"
        },
        {
            "forecastTimeUtc": "2025-01-04 18:00:00",
            "airTemperature": -5.4,
            "feelsLikeTemperature": -5.4,
            "windSpeed": 1,
            "windGust": 4,
            "windDirection": 218,
            "cloudCover": 20,
            "seaLevelPressure": 1013,
            "relativeHumidity": 96,
            "totalPrecipitation": 0,
            "conditionCode": "clear"
        },
        {
            "forecastTimeUtc": "2025-01-04 21:00:00",
            "airTemperature": -5.7,
            "feelsLikeTemperature": -9.1,
            "windSpeed": 2,
            "windGust": 4,
            "windDirection": 190,
            "cloudCover": 15,
            "seaLevelPressure": 1013,
            "relativeHumidity": 97,
            "totalPrecipitation": 0,
            "conditionCode": "clear"
        },
        {
            "forecastTimeUtc": "2025-01-05 00:00:00",
            "airTemperature": -5.1,
            "feelsLikeTemperature": -8.4,
            "windSpeed": 2,
            "windGust": 4,
            "windDirection": 222,
            "cloudCover": 19,
            "seaLevelPressure": 1014,
            "relativeHumidity": 97,
            "totalPrecipitation": 0,
            "conditionCode": "clear"
        },
        {
            "forecastTimeUtc": "2025-01-05 06:00:00",
            "airTemperature": -5,
            "feelsLikeTemperature": -9.5,
            "windSpeed": 3,
            "windGust": 6,
            "windDirection": 240,
            "cloudCover": 53,
            "seaLevelPressure": 1015,
            "relativeHumidity": 96,
            "totalPrecipitation": 0,
            "conditionCode": "cloudy-with-sunny-intervals"
        },
        {
            "forecastTimeUtc": "2025-01-05 12:00:00",
            "airTemperature": -1.2,
            "feelsLikeTemperature": -5.8,
            "windSpeed": 4,
            "windGust": 8,
            "windDirection": 238,
            "cloudCover": 100,
            "seaLevelPressure": 1015,
            "relativeHumidity": 87,
            "totalPrecipitation": 0,
            "conditionCode": "cloudy"
        },
        {
            "forecastTimeUtc": "2025-01-05 18:00:00",
            "airTemperature": -1.3,
            "feelsLikeTemperature": -5.9,
            "windSpeed": 4,
            "windGust": 8,
            "windDirection": 195,
            "cloudCover": 100,
            "seaLevelPressure": 1015,
            "relativeHumidity": 87,
            "totalPrecipitation": 0.2,
            "conditionCode": "light-snow"
        },
        {
            "forecastTimeUtc": "2025-01-06 00:00:00",
            "airTemperature": -1.6,
            "feelsLikeTemperature": -6.3,
            "windSpeed": 4,
            "windGust": 8,
            "windDirection": 172,
            "cloudCover": 100,
            "seaLevelPressure": 1015,
            "relativeHumidity": 87,
            "totalPrecipitation": 0,
            "conditionCode": "cloudy"
        },
        {
            "forecastTimeUtc": "2025-01-06 06:00:00",
            "airTemperature": -2.8,
            "feelsLikeTemperature": -9,
            "windSpeed": 6,
            "windGust": 10,
            "windDirection": 148,
            "cloudCover": 100,
            "seaLevelPressure": 1011,
            "relativeHumidity": 86,
            "totalPrecipitation": 0,
            "conditionCode": "cloudy"
        },
        {
            "forecastTimeUtc": "2025-01-06 12:00:00",
            "airTemperature": -1.4,
            "feelsLikeTemperature": -6.7,
            "windSpeed": 5,
            "windGust": 13,
            "windDirection": 150,
            "cloudCover": 100,
            "seaLevelPressure": 1006,
            "relativeHumidity": 86,
            "totalPrecipitation": 0.4,
            "conditionCode": "light-snow"
        },
        {
            "forecastTimeUtc": "2025-01-06 18:00:00",
            "airTemperature": 0.8,
            "feelsLikeTemperature": -4.5,
            "windSpeed": 6,
            "windGust": 12,
            "windDirection": 164,
            "cloudCover": 100,
            "seaLevelPressure": 1001,
            "relativeHumidity": 92,
            "totalPrecipitation": 5.5,
            "conditionCode": "sleet"
        }
    ]
}
Vieta: Žiegždriai
Dabartinė temperatūra: 5.2 °C
Jaučiama temperatūra: 1.1 °C
Vėjo greitis: 6 m/s
Vėjo gūsiai: 11 m/s
Vėjo kryptis: 249 ° SW
Debesuotumas: 100%
Slėgis jūros lygyje: 1014 hPa, 761 mmHg(Torr)
Santykinė drėgmė: 97%
Krituliai: 0.5 mm
Orų būklė: rain

Process finished with exit code 0
